= Table.ReplaceValue(#"my table", each [Column1], 
  each if [Column2] = "my pattern1" and [Column1] = "my pattern2" then "For hold" 
        else [Column1],Replacer.ReplaceValue,{"Column1"}) 
